package fr.descentecanyon.app.ui.design

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class DcColors(
    val backgroundBase: Color,
    val backgroundElevated: Color,
    val surfaceBase: Color,
    val surfaceRaised: Color,
    val surfaceOverlay: Color,
    val surfacePhotoScrim: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val borderSubtle: Color,
    val borderStrong: Color,
    val primaryAction: Color,
    val primaryActionContent: Color,
    val secondaryAction: Color,
    val water: Color,
    val waterDeep: Color,
    val waterMist: Color,
    val rock: Color,
    val rockLight: Color,
    val forest: Color,
    val snow: Color,
    val topoLine: Color,
    val mapAccent: Color,
    val riskLow: Color,
    val riskMedium: Color,
    val riskHigh: Color,
    val riskExtreme: Color,
    val warning: Color,
    val offline: Color,
    val stale: Color,
    val flowDry: Color,
    val flowTrickle: Color,
    val flowGood: Color,
    val flowHigh: Color,
    val flowVeryHigh: Color,
    val flowFlood: Color,
    val flowUnknown: Color,
)

val DcDarkColors = DcColors(
    backgroundBase = Color(0xFF071118),
    backgroundElevated = Color(0xFF0D1B24),
    surfaceBase = Color(0xFF10212B),
    surfaceRaised = Color(0xFF172B36),
    surfaceOverlay = Color(0xE6111E27),
    surfacePhotoScrim = Color(0xD900080D),
    textPrimary = Color(0xFFF2F6F7),
    textSecondary = Color(0xFFC4D2D7),
    textMuted = Color(0xFF83969E),
    borderSubtle = Color(0x333CC7D9),
    borderStrong = Color(0xFF4FB5C5),
    primaryAction = Color(0xFF55D6EA),
    primaryActionContent = Color(0xFF001F28),
    secondaryAction = Color(0xFF5AC69D),
    water = Color(0xFF3CC7D9),
    waterDeep = Color(0xFF0B5D75),
    waterMist = Color(0xFFBDEDF3),
    rock = Color(0xFFE08A3D),
    rockLight = Color(0xFFFFC082),
    forest = Color(0xFF5AC69D),
    snow = Color(0xFFE7F3F5),
    topoLine = Color(0x334FB5C5),
    mapAccent = Color(0xFF7ED6B5),
    riskLow = Color(0xFF70D69D),
    riskMedium = Color(0xFFFFB84D),
    riskHigh = Color(0xFFFF7A45),
    riskExtreme = Color(0xFFFF4F5E),
    warning = Color(0xFFFFC857),
    offline = Color(0xFF9AA7AD),
    stale = Color(0xFFC48B57),
    flowDry = Color(0xFFB8B0A3),
    flowTrickle = Color(0xFF64CF84),
    flowGood = Color(0xFF3B8DFF),
    flowHigh = Color(0xFFFF8A35),
    flowVeryHigh = Color(0xFFFF4F5E),
    flowFlood = Color(0xFF0B0B0D),
    flowUnknown = Color(0xFF8F9BA1),
)

val DcLightColors = DcColors(
    backgroundBase = Color(0xFFE9EEEB),
    backgroundElevated = Color(0xFFF1F1EC),
    surfaceBase = Color(0xFFFCF8F1),
    surfaceRaised = Color(0xFFF1EAE0),
    surfaceOverlay = Color(0xFFF0E7DB),
    surfacePhotoScrim = Color(0xB8001018),
    textPrimary = Color(0xFF122029),
    textSecondary = Color(0xFF39515A),
    textMuted = Color(0xFF627278),
    borderSubtle = Color(0xFFC7D6D7),
    borderStrong = Color(0xFF317E8C),
    primaryAction = Color(0xFF087E93),
    primaryActionContent = Color.White,
    secondaryAction = Color(0xFF287D55),
    water = Color(0xFF087E93),
    waterDeep = Color(0xFF065469),
    waterMist = Color(0xFFCFE6EA),
    rock = Color(0xFFB76022),
    rockLight = Color(0xFFD9B083),
    forest = Color(0xFF287D55),
    snow = Color(0xFFFFFFFF),
    topoLine = Color(0x55317E8C),
    mapAccent = Color(0xFF287D55),
    riskLow = Color(0xFF287D55),
    riskMedium = Color(0xFF9F6B00),
    riskHigh = Color(0xFFC14C12),
    riskExtreme = Color(0xFFB42131),
    warning = Color(0xFF9F6B00),
    offline = Color(0xFF687A81),
    stale = Color(0xFF8A5D2E),
    flowDry = Color(0xFF77716A),
    flowTrickle = Color(0xFF16883B),
    flowGood = Color(0xFF005FD1),
    flowHigh = Color(0xFFD75D00),
    flowVeryHigh = Color(0xFFD9001B),
    flowFlood = Color(0xFF111111),
    flowUnknown = Color(0xFF777F84),
)

fun DcColors.toMaterialColorScheme(darkTheme: Boolean): ColorScheme {
    return if (darkTheme) {
        darkColorScheme(
            primary = primaryAction,
            onPrimary = primaryActionContent,
            primaryContainer = waterDeep,
            onPrimaryContainer = waterMist,
            secondary = secondaryAction,
            onSecondary = Color(0xFF002115),
            secondaryContainer = forest.copy(alpha = 0.24f),
            onSecondaryContainer = Color(0xFFD2F8E7),
            tertiary = rock,
            onTertiary = Color(0xFF2F1600),
            background = backgroundBase,
            onBackground = textPrimary,
            surface = surfaceBase,
            onSurface = textPrimary,
            surfaceVariant = surfaceRaised,
            onSurfaceVariant = textSecondary,
            outline = borderStrong,
            outlineVariant = borderSubtle,
            error = riskExtreme,
            onError = Color.White,
        )
    } else {
        lightColorScheme(
            primary = primaryAction,
            onPrimary = primaryActionContent,
            primaryContainer = waterMist,
            onPrimaryContainer = Color(0xFF07333B),
            secondary = secondaryAction,
            onSecondary = Color.White,
            secondaryContainer = Color(0xFFD9F0E2),
            onSecondaryContainer = Color(0xFF06351F),
            tertiary = rock,
            onTertiary = Color.White,
            background = backgroundBase,
            onBackground = textPrimary,
            surface = surfaceBase,
            onSurface = textPrimary,
            surfaceVariant = surfaceRaised,
            onSurfaceVariant = textSecondary,
            outline = borderStrong,
            outlineVariant = borderSubtle,
            error = riskExtreme,
            onError = Color.White,
        )
    }
}

val LocalDcColors = staticCompositionLocalOf { DcDarkColors }
